### PR TITLE
Fall back to user_principal_name if upn is not defined.

### PR DESCRIPTION
**Pull request by BrandonEvansAsurion**
Before:

image

After:

image

### CODE REVIEW

**Comment by BrandonEvansAsurion** [comment]
Pushed a commit requesting the OpenID scope, allowing us to extract a more user-friendly name from the ID token. This is now the result:

image

**Comment by Yshayy** [comment]
I think we should add a unit test for all the extraction & formatting logic as it a bit complex.

**Comment by Yshayy** [comment]
I don’t see any server specific unit tests (most functionality is covered in e2e, integration tests), but it should be under the spec folder, in a similar fashion to the clients tests.
In any case, it should be small as the entire functionality of the editor server side logic will be removed in the future in favor of the gateway.

**Comment by lucas-rudd** [comment]
giphy

**Comment by BrandonEvansAsurion** [comment]
Closing and created a [new PR](https://github.com/Soluto/tweek/pull/852) from within the same repository.

**Pull request closed without merging**
