### PR TITLE
Added /configurations endpoint

### LINKED ISSUE #962: Add /configurations route for api
Currently we don't pass through /configurations route, need to add it to the gateway

### PR DESCRIPTION
**Pull request by michaelkruglos**
closes #962

### CODE REVIEW

**Comment by Yshayy** [comment]
Maybe it's worthing using MainRouter.prefix("/configurations/").subrouter() directly in passthrough call? (main.go)
The struct of the router is getting complicated....

**Comment by Yshayy** [comment]
Like:
https://github.com/Soluto/tweek/blob/gateway/services/gateway/main.go#L89

**Comment by michaelkruglos** [comment]
I wouldn't say it's complicated, it has only 6 entries with this addition. Besides, it would be strange to mount this specific route in a different way.

**Comment by Yshayy** [comment]
Since it's clearly a patch for legacy, isn't it better to put it in one line in one place (maybe with comment)?

**Pull request merged**
