### PR TITLE
Added code to output basic auth password after keys generation

### PR DESCRIPTION
**Pull request by michaelkruglos**
Added code to output basic auth password after keys generation

### CODE REVIEW

**Comment by Yshayy** [comment]
Isn't it a problem that it requires python?

**Comment by Yshayy** [comment]
And maybe it's worth writing to file

**Comment by michaelkruglos** [comment]
There's no easy way to do it without python, that I know of. Python should be available on all Macs and Linux boxes, and is somewhat expected to be installed on developer's Windows boxes.

**Comment by Yshayy** [comment]
It's worth adding it to https://github.com/Soluto/tweek-deploy/pull/3/files

**Pull request merged**
