### PR TITLE
feat(editor): added markdown support for the description of keys

### LINKED ISSUE #724: Use markdown in key description
Hi,
I wanna add markdown support on the key description area.

I'll open a pr when I'm done.

Thanks!

### PR DESCRIPTION
**Pull request by noamokman**
Hi,
This closes #724.
Let me know what you think.

Thanks 😄

### CODE REVIEW

**Comment by Yshayy** [comment]
http://www.rricard.me/draft-md/ (or other draft.js based markdown editor) might be more suited for this case

**Comment by noamokman** [comment]
image

**Comment by noamokman** [comment]
@Yshayy merge this

**Comment by tal952** [comment]
Why isn't it being merged?

**Pull request closed without merging**
