### PR TITLE
Added support for requesting policies in gateway

### PR DESCRIPTION
**Pull request by Gabrn**

### CODE REVIEW

**Comment by Yshayy** [comment]
Isn't it already supported?
https://github.com/Soluto/tweek/blob/master/services/gateway/swagger.yml

**Comment by Gabrn** [comment]
No it is not, it is only supported for requests containing tweek admin token but not for requests from other authProviders because currently requestUtils.go will always throw an error "Invalid request path".

**Comment by Yshayy** [comment]
Is that the behavior for all policies apis? get/patch/post?

**Comment by Gabrn** [comment]
Yes.. all of them will result in an error (unless the request contains tweek admin token).

**Comment by Yshayy** [comment]
We should probably add write permission to repo/policies to base git repo images.
https://github.com/Soluto/tweek/tree/master/services/git-service/BareRepository

**Comment by Yshayy** [comment]
Doesn't it makes it less consistent with our permission model?

**Comment by Gabrn** [comment]
I think that it should be alright to give different permission objects to different resources.
Some resources such as revision-history use the repo object for both read and write.
Schemas for example uses repo for read but repo/schemas for write.
I view policies as something that requires more permissions to read than reading schemas or tags for example. 
I can't think of a particular reason to block an editor user from seeing schemas but I don't want every user to know all the permissions for all other users.

**Comment by Yshayy** [comment]
I've updated my comment :)

**Comment by Yshayy** [comment]
Hmm, I think revision-history has no write functionality, and use read "repo" as well.

**Comment by Gabrn** [comment]
True, revision-history only has GET api.
Still if you take github as an example and you think of reading files as reading keys, the logic holds that I can view files but i can't access settings and see all collaborators as I'm not admin.

**Pull request merged**
