### PR TITLE
Allow to set multiple couchbase bootstrap servers

### PR DESCRIPTION
**Pull request by AleF83**
This PR allows to set multiple bootstrap servers for Couchbase db.

According to Couchbase documentation:

> The client attempts to bootstrap off of each of these servers. When it successfully connects with one of the servers in this list, the bootstrapping process ends.

So setting multiple servers from the cluster will improve connection stability in case of failure of the first server.

### CODE REVIEW

**Review by tomeresk — APPROVED** [review]

**Comment by Yshayy** [comment]
Why not use:
https://github.com/brantburnett/Couchbase.Extensions/blob/master/docs/dns-srv.md

**Comment by Yshayy** [comment]
Why not use:
https://github.com/brantburnett/Couchbase.Extensions/blob/master/docs/dns-srv.md

**Comment by Yshayy** [comment]
That way, you don't need to keep maintaining this list in different deployments

**Comment by Yshayy** [comment]
Also, this change is not backward compatible, please revert and remove this version

**Pull request merged**
