### PR TITLE
Fix: Firefox ui issues

### PR DESCRIPTION
**Pull request by tal952**
#943 
* The css "zoom" attribute is not supported by Firefox.
Using transform: scale instead.

* Fix Firefox overflow issue
https://stackoverflow.com/questions/44948158/flexbox-overflow-issue-in-firefox

### CODE REVIEW

**Comment by tal952** [comment]
@rosensj can you please review it?

**Comment by rosensj** [comment]
I approved this but if you're looking for issues with tweek and firefox there's also #943

**Comment by tal952** [comment]
> I approved this but if you're looking for issues with tweek and firefox there's also #943

Thank you :)

I fixed the issue after I saw it in #943 :+1:

**Comment by tal952** [comment]
I added another fix, so it will close #943

**Pull request merged**
