### PR TITLE
Added the ability to configure a set of allowed user groups for OAuth2 authentication.

### PR DESCRIPTION
**Pull request by BrandonEvansAsurion**
This PR modifies the OAuth2 provider to validate that the authenticated user belongs to one of the (AD) groups defined in `AUTH_OAUTH2_ALLOWED_GROUPS`. If this environment variable isn't defined, the provider's functionality doesn't change.

### CODE REVIEW

**Comment by BrandonEvansAsurion** [comment]
It might be beneficial to allow Tweek to be configured such that the user must be in a set of AD groups instead of authorizing the user if they are in any of the allowed groups. Any suggestions on how to structure the environment variable(s) to support both use-cases?

**Comment by nataly87s** [comment]
maybe make it more generic? support other claims as well, not only groups

**Comment by BrandonEvansAsurion** [comment]
This PR is unnecessary as many OAuth2 providers allow for these restrictions to be configured on their side. Closing for now.

**Comment by BrandonEvansAsurion** [comment]
If something like this is ever used in the future, the `openid` will need to be requested in order for the ID token to be returned.

**Pull request closed without merging**
