### PR TITLE
Fix: authoring fail to start

### PR DESCRIPTION
**Pull request by tal952**
When using a big rules repo, the clone takes a while and the authoring fail to start.

### CODE REVIEW

**Comment by Yshayy** [comment]
There should be some timeout, maybe it should be configurable?
What's the size of the repo you're trying to clone? 
Additionally, Authoring should clone the data from publishing service and in most cases, both services will be in the same network?

**Comment by tal952** [comment]
Actually, in our case the repo is not big, but just sitting in gitlab and it takes some time to get it.
The problem happen when you change the docker-compose.override.yml file from pointing to the local git service to gitlab repo, and then yarn start.

Because the clone process and the publishing service start process are detached, the publishing service start process finish quicker and signal as healthy. Then the authoring is starting and he cant access the repo.

**Comment by Yshayy** [comment]
Maybe it’s better than for the authoring to wait for the publishing to return healthy. (There’s an health endpoint, and the http server is available only the cloning is complete)

**Comment by Gabrn** [comment]
> Maybe it’s better than for the authoring to wait for the publishing to return healthy. (There’s an health endpoint, and the http server is available only the cloning is complete)

Yeah it's another option... Why do you think it's a bad idea for publishing to finish cloning the repo before the init-git script continues?

**Comment by Yshayy** [comment]
Because of publishing is not available (for example, authoring is up before publishing) it won't work waiting.
But if we wait for publishing to return healthy, the startup order won't be relevant

**Comment by Yshayy** [comment]
Isn't the process run synchronously? What "wait;" solves?

**Comment by tal952** [comment]
The su command is asynchronous and the wait; command make it synchronous,  according to:
https://superuser.com/questions/751300/how-do-i-run-su-username-c-command-in-a-sequence

**Comment by tal952** [comment]
Can be merged? @michaelkruglos @Yshayy

**Pull request closed without merging**
